// get all exercises
export const GET_ALL_EXERCISES_REQUEST = 'GET_ALL_EXERCISES_REQUEST';
export const GET_ALL_EXERCISES_SUCCESS = 'GET_ALL_EXERCISES_SUCCESS';
export const GET_ALL_EXERCISES_FAILURE = 'GET_ALL_EXERCISES_FAILURE';

// create exercise
export const CREATE_EXERCISE_REQUEST = 'CREATE_EXERCISE_REQUEST';
export const CREATE_EXERCISE_SUCCESS = 'CREATE_EXERCISE_SUCCESS';
export const CREATE_EXERCISE_FAILURE = 'CREATE_EXERCISE_FAILURE';

// delete an exercise
export const DELETE_EXERCISE_REQUEST = 'DELETE_EXERCISE_REQUEST';
export const DELETE_EXERCISE_SUCCESS = 'DELETE_EXERCISE_SUCCESS';
export const DELETE_EXERCISE_FAILURE = 'DELETE_EXERCISE_FAILURE';

// get exercise
export const GET_EXERCISE_REQUEST = 'GET_EXERCISE_REQUEST';
export const GET_EXERCISE_SUCCESS = 'GET_EXERCISE_SUCCESS';
export const GET_EXERCISE_FAILURE = 'GET_EXERCISE_FAILURE';

// change exercise name
export const CHANGE_EXERCISE_NAME_REQUEST = 'CHANGE_EXERCISE_NAME_REQUEST';
export const CHANGE_EXERCISE_NAME_SUCCESS = 'CHANGE_EXERCISE_NAME_SUCCESS';
export const CHANGE_EXERCISE_NAME_FAILURE = 'CHANGE_EXERCISE_NAME_FAILURE';

// clear exercise
export const CLEAR_EXERCISE = 'CLEAR_EXERCISE';
