// get all exercises
export const GET_ALL_EXERCISES_REQUEST = 'GET_ALL_EXERCISES_REQUEST';
export const GET_ALL_EXERCISES_SUCCESS = 'GET_ALL_EXERCISES_SUCCESS';
export const GET_ALL_EXERCISES_FAILURE = 'GET_ALL_EXERCISES_FAILURE';

// delete an exercise
export const DELETE_EXERCISE_REQUEST = 'DELETE_EXERCISE_REQUEST';
export const DELETE_EXERCISE_SUCCESS = 'DELETE_EXERCISE_SUCCESS';
export const DELETE_EXERCISE_FAILURE = 'DELETE_EXERCISE_FAILURE';
