// get all exercises
export const GET_ALL_EXERCISES_REQUEST = 'GET_ALL_EXERCISES_REQUEST';
export const GET_ALL_EXERCISES_SUCCESS = 'GET_ALL_EXERCISES_SUCCESS';
export const GET_ALL_EXERCISES_FAILURE = 'GET_ALL_EXERCISES_FAILURE';

// delete an exercise
export const DELETE_EXERCISE_REQUEST = 'DELETE_EXERCISE_REQUEST';
export const DELETE_EXERCISE_SUCCESS = 'DELETE_EXERCISE_SUCCESS';
export const DELETE_EXERCISE_FAILURE = 'DELETE_EXERCISE_FAILURE';

// get exercise
export const GET_EXERCISE_REQUEST = 'GET_EXERCISE_REQUEST';
export const GET_EXERCISE_SUCCESS = 'GET_EXERCISE_SUCCESS';
export const GET_EXERCISE_FAILURE = 'GET_EXERCISE_FAILURE';

// delete Inout
export const DELETE_EXERCISE_INPUT_REQUEST = 'DELETE_EXERCISE_INPUT_REQUEST';
export const DELETE_EXERCISE_INPUT_SUCCESS = 'DELETE_EXERCISE_INPUT_SUCCESS';
export const DELETE_EXERCISE_INPUT_FAILURE = 'DELETE_EXERCISE_INPUT_FAILURE';

// add input
export const ADD_EXERCISE_INPUT_REQUEST = 'ADD_EXERCISE_INPUT_REQUEST';
export const ADD_EXERCISE_INPUT_SUCCESS = 'ADD_EXERCISE_INPUT_SUCCESS';
export const ADD_EXERCISE_INPUT_FAILURE = 'ADD_EXERCISE_INPUT_FAILURE';

// change exercise name
export const CHANGE_EXERCISE_NAME_REQUEST = 'CHANGE_EXERCISE_NAME_REQUEST';
export const CHANGE_EXERCISE_NAME_SUCCESS = 'CHANGE_EXERCISE_NAME_SUCCESS';
export const CHANGE_EXERCISE_NAME_FAILURE = 'CHANGE_EXERCISE_NAME_FAILURE';

// clear exercise
export const CLEAR_EXERCISE = 'CLEAR_EXERCISE';
