// delete Inout
export const DELETE_INPUT_REQUEST = 'DELETE_INPUT_REQUEST';
export const DELETE_INPUT_SUCCESS = 'DELETE_INPUT_SUCCESS';
export const DELETE_INPUT_FAILURE = 'DELETE_INPUT_FAILURE';

// add input
export const ADD_INPUT_REQUEST = 'ADD_INPUT_REQUEST';
export const ADD_INPUT_SUCCESS = 'ADD_INPUT_SUCCESS';
export const ADD_INPUT_FAILURE = 'ADD_INPUT_FAILURE';
