// Get unfinished workouts
export const GET_UNFINISHED_WORKOUTS_REQUEST =
  'GET_UNFINISHED_WORKOUTS_REQUEST';
export const GET_UNFINISHED_WORKOUTS_SUCCESS =
  'GET_UNFINISHED_WORKOUTS_SUCCESS';
export const GET_UNFINISHED_WORKOUTS_FAILURE =
  'GET_UNFINISHED_WORKOUTS_FAILURE';

export const CLEAR_QUICKSTART = 'CLEAR_QUICKSTART';
