// Create Workout
export const CREATE_WORKOUT_REQUEST = 'CREATE_WORKOUT_REQUEST';
export const CREATE_WORKOUT_SUCCESS = 'CREATE_WORKOUT_SUCCESS';
export const CREATE_WORKOUT_FAILURE = 'CREATE_WORKOUT_FAILURE';

// GET Workout
export const GET_WORKOUT_REQUEST = 'GET_WORKOUT_REQUEST';
export const GET_WORKOUT_SUCCESS = 'GET_WORKOUT_SUCCESS';
export const GET_WORKOUT_FAILURE = 'GET_WORKOUT_FAILURE';

// GET Workouts
export const GET_WORKOUTS_REQUEST = 'GET_WORKOUTS_REQUEST';
export const GET_WORKOUTS_SUCCESS = 'GET_WORKOUTS_SUCCESS';
export const GET_WORKOUTS_FAILURE = 'GET_WORKOUTS_FAILURE';

// Delete Workout
export const DELETE_WORKOUT_REQUEST = 'DELETE_WORKOUT_REQUEST';
export const DELETE_WORKOUT_SUCCESS = 'DELETE_WORKOUT_SUCCESS';
export const DELETE_WORKOUT_FAILURE = 'DELETE_WORKOUT_FAILURE';

// Add Exercise to workout
export const ADD_EXERCISE_TO_WORKOUT_REQUEST =
  'ADD_EXERCISE_TO_WORKOUT_REQUEST';
export const ADD_EXERCISE_TO_WORKOUT_SUCCESS =
  'ADD_EXERCISE_TO_WORKOUT_SUCCESS';
export const ADD_EXERCISE_TO_WORKOUT_FAILURE =
  'ADD_EXERCISE_TO_WORKOUT_FAILURE';

export const CLEAR_WORKOUT = 'CLEAR_WORKOUT';
