// Create Workout
export const CREATE_WORKOUT_REQUEST = 'CREATE_WORKOUT_REQUEST';
export const CREATE_WORKOUT_SUCCESS = 'CREATE_WORKOUT_SUCCESS';
export const CREATE_WORKOUT_FAILURE = 'CREATE_WORKOUT_FAILURE';

// GET Workout
export const GET_WORKOUT_REQUEST = 'GET_WORKOUT_REQUEST';
export const GET_WORKOUT_SUCCESS = 'GET_WORKOUT_SUCCESS';
export const GET_WORKOUT_FAILURE = 'GET_WORKOUT_FAILURE';

// GET Workouts
export const GET_WORKOUTS_REQUEST = 'GET_WORKOUTS_REQUEST';
export const GET_WORKOUTS_SUCCESS = 'GET_WORKOUTS_SUCCESS';
export const GET_WORKOUTS_FAILURE = 'GET_WORKOUTS_FAILURE';

export const CLEAR_WORKOUT = 'CLEAR_WORKOUT';
